name: Publish new theme version

on:
  push:
    tags:
      - "*" # any tag, e.g. 1.0.0

permissions:
  contents: write # required to create the release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --notes="" \
            manifest.json theme.css
